name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: install dot
      run: brew install dot
      
    - name: install doygen
      run: brew install doxygen
      
    - name: run cmake
      run: cmake . -DCMAKE_INSTALL_PREFIX=install -G "Xcode"
      
    - name: build debug build
      run: cmake --build . --config Debug --target install
      
      
