name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
      
    - name: install swig
      run: brew install swig
      
    - name: install lua
      run: brew install lua 
      
    - name: run cmake
      run: cmake . -DCMAKE_INSTALL_PREFIX=install -G "Xcode"
      
    - name: build the debug build
      run: cmake --build . --config Debug --target SDLSkeleton
      
      
